### ISSUE TITLE
Not all debian 7 images have curl installed

### ISSUE THREAD

**Issue by matjohn2** [packetbeat/packetbeat-deploy#6]
Hi.

Debian 7 as offered in AWS Marketplace does not have curl installed by default.

Ansible-playbook run fails on ES nodes unless an 'install curl' job is added to roles/esnode/tasks/main.yml as follows:

- name: Install curl
  apt: pkg=curl update_cache=yes state=latest
  tags: deps

Will submit a PR once the installation is successful.

AWS AMI is: debian-wheezy-amd64-pvm-2014-10-18-ebs-8e939b13-41b6-40bc-b2ba-481f2d6c5d79-ami-2058e248.2 (ami-2278cc55)

**Comment by catalyzeVince** [comment]
+1
