### ISSUE TITLE
esnode fails on ubuntu

### ISSUE THREAD

**Issue by uptop-adelgado** [packetbeat/packetbeat-deploy#7]
Hello: I'm trying packetbeat from the first time, it looks a lot nicer than my manually created kibana dashboard, plus I think it's pretty great to have extra information that's not normally provided by log files.

When installing it using packetbeat-deploy I ran into a couple of issues:

```
TASK: [esnode | Install Java7] ************************************************
failed: [************] => {"failed": true, "item": ""}
stderr: E: Package 'java7-runtime-headless' has no installation candidate
```
Solved by modifying the role with the specific java package

```
TASK: [esnode | Add Elasticsearch repository] *********************************
failed: [************] => {"failed": true, "item": ""}
msg: Could not import python modules: pycurl. Please install python-pycurl package.

FATAL: all hosts have already failed -- aborting
```
Solved by manual pycurl installation

```
TASK: [esnode | Download Packetbeat Dashboards] *******************************
failed: [*************] => {"failed": true, "item": ""}
msg: Failed to validate the SSL certificate for github.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting
```
I tried updating the ca certificates, but it's not working for me, Suggestions?

Also there's a couple of typos here: http://packetbeat.com/deploy
```
# packetbeat-deploy/hosts

[aggrgator]
10.50.10.15
```

**Comment by tsg** [comment]
We don't officially support Ubuntu in packetbeat-deploy, but sounds like we could/should. 

Many thanks for reporting these issues.

Regarding the certs issue, it seems related to this: https://github.com/ansible/ansible/issues/7218
What ansible version do you have?

**Comment by uptop-adelgado** [comment]
Sorry about the delay getting back to you, Yes, the certificate problem was related to the ansible version as described on the linked issue.

Thanks!
