### ISSUE TITLE
how to access kibana?

### ISSUE THREAD

**Issue by dublx** [packetbeat/packetbeat-deploy#8]
Right, so I started the VM's, now where can I find the kibana dashboard?

Thanks

**Comment by tsg** [comment]
If the ansible tasks were completed successfully, you should be able to access Kibana simply at `http://<your-aggregator-ip-address>/`

**Comment by dublx** [comment]
Got it, I had missed running the Ansible playbook. I assumed the Vagrantfile called Ansible directly.
